### ISSUE TITLE
Weather reports don't select weather stations properly

### ISSUE THREAD

**Issue by danielg4** [xray7224/MegBot#56]
[Sun 2013-03-24 09:21:51 AM PDT] DonkeyHotei: !weather 94112
[Sun 2013-03-24 09:21:53 AM PDT] MegBot: [San Francisco, CA, United States] Condition: Partly Cloudy | Temp: 9C/48F/282K | Humidity: 83% | Wind Speed 0mph/0kmph 
[Sun 2013-03-24 09:21:56 AM PDT] DonkeyHotei: !weather 94127
[Sun 2013-03-24 09:21:57 AM PDT] MegBot: [San Francisco, CA, United States] Condition: Partly Cloudy | Temp: 9C/48F/282K | Humidity: 83% | Wind Speed 0mph/0kmph 
[Sun 2013-03-24 09:22:31 AM PDT] DonkeyHotei: it shows identical results for different postal/zip codes! that's a bug, people!
[Sun 2013-03-24 09:22:37 AM PDT] Tsyesika: is it
[Sun 2013-03-24 09:23:23 AM PDT] DonkeyHotei: http://www.wunderground.com/cgi-bin/findweather/hdfForecast?query=94112
[Sun 2013-03-24 09:23:25 AM PDT] DonkeyHotei: http://www.wunderground.com/cgi-bin/findweather/hdfForecast?query=94127
[Sun 2013-03-24 09:24:14 AM PDT] Tsyesika: how about you link me to the API megbot uses :P
[Sun 2013-03-24 09:24:56 AM PDT] Tsyesika: i'll dump it out and look
[Sun 2013-03-24 09:24:59 AM PDT] DonkeyHotei: if the api can't tell the difference between different parts of town, it's a bad api
[Sun 2013-03-24 09:25:26 AM PDT] Tsyesika: it might, the weather might just be the same
[Sun 2013-03-24 09:26:15 AM PDT] DonkeyHotei: well, then i'll try a couple of parts of town that never have the same weather as here
[Sun 2013-03-24 09:26:20 AM PDT] DonkeyHotei: !weather 94124
[Sun 2013-03-24 09:26:21 AM PDT] MegBot: [San Francisco, CA, United States] Condition: Partly Cloudy | Temp: 9C/48F/282K | Humidity: 83% | Wind Speed 0mph/0kmph 
[Sun 2013-03-24 09:26:24 AM PDT] DonkeyHotei: !weather 94107
[Sun 2013-03-24 09:26:25 AM PDT] MegBot: [San Francisco, CA, United States] Condition: Partly Cloudy | Temp: 9C/48F/282K | Humidity: 83% | Wind Speed 0mph/0kmph

**Comment by moggers87** [comment]
This plugin has been removed
