### ISSUE TITLE
Replace MegWorld APIs

### ISSUE THREAD

**Issue by moggers87** [xray7224/MegBot#75]
Currently we rely on the MegWorld APIs to proxy anything that requires an API key. This hasn't been touched for years, is written in PHP and is a huge fire hazard!

I'm pretty sure only the WOEID API is being proxied - however, last time I looked it needed a WOEID. We can get Lat/Long from Google without an API key, so we just need to find a keyless API for weather.

**Comment by moggers87** [comment]
Weather API, apparently keyless: http://www.metaweather.com/about/

**Comment by shymega** [comment]
It would be interesting to see if it stays that way, seems too good to be true, especially being a keyless API. 

I would be intriged to see what comes out of this issue, and the API itself. Might use this for [ShyBotMk2](https://github.com/shymega/shybotmk2). Anyway, just my view on the matter.

**Comment by moggers87** [comment]
No longer needed as the weather plugin as been removed, see #78
